#!/usr/bin/env ruby

require_relative '../lib/rule_engine'
require 'json'
require 'optparse'
require 'optparse/uri'
require_relative '../lib/visitors/configuration_visitor'
require_relative '../lib/facades/configuration_file_facade'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: puppet-sec-lint [options]"

  opts.on("-f", "--file FILE",URI, "Path of puppet file to be analyzed") do |file|
    options[:file] = file
  end
end.parse!

if options[:file].nil?
  linter_server = Thread.new {
  require_relative '../lib/servers/linter_server'
  }
  language_server = Thread.new {
  require_relative '../lib/servers/language_server'
  LanguageServer.start
  }

  linter_server.join
  language_server.join
  exit
end

ConfigurationVisitor.GenerateIDs
ConfigurationFileFacade.LoadConfigurations

File.open(options[:file].to_s, 'rb:UTF-8') do |f|
  code = f.read

  result = RuleEngine.analyzeDocument(code)

  result.each do |sin|
    puts sin.ToString
  end
end